[workers]
worker1 ansible_host=YOUR_PUBLIC_IP_1 ansible_user=ubuntu ansible_ssh_private_key_file=key.pem
worker2 ansible_host=YOUR_PUBLIC_IP_2 ansible_user=ubuntu ansible_ssh_private_key_file=key.pem
worker3 ansible_host=YOUR_PUBLIC_IP_2 ansible_user=ubuntu ansible_ssh_private_key_file=key.pem